# Generated by Django 5.0.3 on 2024-05-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reset_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
