# Generated by Django 5.0.3 on 2024-05-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
