# Generated by Django 5.0.3 on 2024-05-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_remove_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_requirements',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
