# Generated by Django 5.0.3 on 2024-05-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_task_ai_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='ai_requirements',
        ),
        migrations.AddField(
            model_name='project',
            name='ai_requirements',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
