# Generated by Django 5.0.3 on 2024-05-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_task_deadline_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slack_channel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
