# Generated by Django 5.0.3 on 2024-05-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_remove_task_developer_task_developers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ai_requirements',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slack_channel_id',
        ),
        migrations.AddField(
            model_name='project',
            name='edited_functional_requirements',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='edited_non_functional_requirements',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='functional_requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='non_functional_requirements',
            field=models.JSONField(default=list),
        ),
    ]
