# Generated by Django 5.0.3 on 2024-06-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_task_end_time_task_start_time_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_time_m',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time_m',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
