# Generated by Django 5.0.3 on 2024-06-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_task_end_time_m_task_start_time_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
    ]
