# Generated by Django 5.0.3 on 2024-06-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_remove_task_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='end_time_m',
            new_name='manager_end_time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='start_time_m',
            new_name='manager_start_time',
        ),
    ]
