# Generated by Django 5.0.3 on 2024-06-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_developermetrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developermetrics',
            name='code_quality_score',
        ),
        migrations.RemoveField(
            model_name='developermetrics',
            name='commits',
        ),
        migrations.RemoveField(
            model_name='developermetrics',
            name='issue_resolution_time',
        ),
        migrations.AddField(
            model_name='task',
            name='actual_time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
